apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valencia-juiceshop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/cavalen/cicd-demo.git"
    path: app
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: valencia
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
